### ISSUE TITLE
zmena webu

### ISSUE THREAD

**Issue by bodyguardroman** [kodi-czsk/plugin.video.ta3.com#1]
kedze je zmeneny web plugin prestal fungovat,mimochodom mohlo byt byt zakompovane do pluginu aj vyber kvality videa?oni pri videu maju na vyber z troch kvalit

**Comment by mx3L** [comment]
ciastocne opravene,
Kvalita videa je prednastavena na najlepsiu. Pre vyber z inych kvalit je mozne zmenit "Video quality" polozku v nastaveniach pluginu.

**Comment by bodyguardroman** [comment]
hej lebo este to kompletne nefunguje,lebo po kliknuti sa zobrazi iba prazdne pole

**Comment by mx3L** [comment]
Co presne nefunguje?

**Comment by bodyguardroman** [comment]
napr.tuknem na publicistiku,ale tam je lne latest video(tiez prazdne)
podla datumu(tiez iba datum a prazdne ziadne videa na prehratie)
mimochodom predchadzajuca verzia mala relacie v zlozkach,aj teraz je to tak na webe:
http://www.ta3.com/publicistika/173/svet-technologii.html

**Comment by bodyguardroman** [comment]
uz to funguje,len plugin sa mi neaktulizoval automaticky,musel som rucne stiahnut.(mimochodom nevies poradit kde sa daju aktulizovat pluginy,lebo mam kodi 15.2 helix,tam sa to rucne neda(ze kliknut na aktualizovat pluginy

**Comment by mx3L** [comment]
Ok vdaka za info.

Zobraz nainstalovane repozitare, v lavom rohu vytiahni bocne menu(standardny skin) a daj aktualizovat
