### ISSUE TITLE
zložky

### ISSUE THREAD

**Issue by bodyguardroman** [kodi-czsk/plugin.video.ta3.com#2]
pravdepodobne niečo menili na stranke,pretože napr.pri vybere relacie svet technologii.sa tam nezobrazia epizody tej relacie,ale aj epizody inych relacii...

**Comment by mrRobit** [comment]
Spominany problem od @bodyguardroman sa objavuje vo vsetkych relaciach, avsak len niekedy. Niekedy sa pri otvoreni relacie zobrazia spravne epizody a pri opatovnom prekliknuti na inu relaciu a spat sa uz zobrazuju nespravne epizody.

**Comment by mx3L** [comment]
Pozrel som to a ta3 vyhladavanie na web stranke obcas produkuje korektne vysledky, tj pouzije sa vybrany filter a obcas vobec nefunguje, tj zobrazi posledne pridane relacie bez pouzitia vybraneho filtra. 
Snad to opravia.

**Comment by mrRobit** [comment]
Napisal som na web@ta3.com s opisom problemu, cakam na ich odpoved, resp. vyriesenie problemu.

**Comment by mrRobit** [comment]
Z pluginu / webu bola odstranena moznost vyhladavat relacie podla nazvu, zostala uz len moznost vyhladavania podla datumu.
Tato issue je uz teda irelevantna.

**Comment by mx3L** [comment]
V 1.1.3 by malo vsetko fungovat ako ma
